package sh.zolt.jarproof.engine;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.zip.GZIPInputStream;
import org.junit.jupiter.api.Test;

/**
 * Proves the committed symbol resources still match the pinned toolchain's signature archive.
 *
 * <p>On a mismatch the regenerated bytes are written under {@code target/} and the failure
 * message says exactly how to adopt them, so refreshing a resource is a copy rather than an
 * archaeology exercise.
 */
final class JdkSymbolResourceFreshnessTest {
    private static final String RESOURCE_DIRECTORY =
            "modules/jarproof-engine/src/main/resources/sh/zolt/jarproof/engine";

    @Test
    void bundledJavaSeventeenSymbolsMatchTheToolchain() throws IOException {
        assertResourceIsFresh(17);
    }

    @Test
    void theToolchainShipsTheSignatureArchiveTheGeneratorNeeds() {
        Path ctSym = JdkSymbolResourceGenerator.toolchainCtSym();

        assertTrue(Files.isRegularFile(ctSym), () -> "No signature archive at " + ctSym);
    }

    private static void assertResourceIsFresh(int javaRelease) throws IOException {
        String name = JdkSymbolCatalog.resourceName(javaRelease);
        byte[] regenerated = JdkSymbolResourceGenerator.resourceBytes(javaRelease);
        byte[] committed = committedBytes(name);
        if (Arrays.equals(committed, regenerated)) {
            assertEquals(javaRelease, JdkSymbolCatalog.forRelease(javaRelease).javaRelease());
            return;
        }

        Path rescued = Path.of("target", "regenerated-" + name).toAbsolutePath();
        Files.createDirectories(rescued.getParent());
        Files.write(rescued, regenerated);
        fail(staleMessage(name, rescued, committed, regenerated));
    }

    private static String staleMessage(String name, Path rescued, byte[] committed, byte[] regenerated) {
        String reason = committed.length == 0
                ? "is not committed yet"
                : Arrays.equals(text(committed), text(regenerated))
                        ? "holds the same symbol text but a different gzip container, which means the"
                                + " toolchain's compressor changed"
                        : "no longer matches the toolchain's signature archive";
        return "The bundled resource " + name + " " + reason + "."
                + System.lineSeparator() + "Adopt the regenerated bytes with:"
                + System.lineSeparator() + "  cp " + rescued + " " + RESOURCE_DIRECTORY + "/" + name;
    }

    private static byte[] committedBytes(String name) throws IOException {
        try (InputStream resource = JdkSymbolCatalog.class.getResourceAsStream(name)) {
            return resource == null ? new byte[0] : resource.readAllBytes();
        }
    }

    private static byte[] text(byte[] compressed) {
        if (compressed.length == 0) {
            return compressed;
        }
        try (GZIPInputStream gzip = new GZIPInputStream(new ByteArrayInputStream(compressed))) {
            return gzip.readAllBytes();
        } catch (IOException unreadable) {
            return unreadable.toString().getBytes(StandardCharsets.UTF_8);
        }
    }
}
