package sh.zolt.jarproof.cli;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;

/**
 * Picocli derives its command model from annotations at runtime, and native-image keeps no
 * annotation or reflective member it was not told about. Without the metadata the native binary
 * fails on the first parse -- observed as {@code AutoHelpMixin ... is not a command} -- while every
 * JVM build stays green. The metadata is generated by the {@code info.picocli:picocli-codegen}
 * annotation processor declared in this member's {@code zolt.toml}, which is exactly what this test
 * pins: remove the processor entry and the generated file disappears with it.
 */
final class NativeReflectionConfigTest {
    private static final String CONFIG = "/META-INF/native-image/picocli-generated/reflect-config.json";
    private static final Pattern NAME = Pattern.compile("\"name\"\\s*:\\s*\"([^\"]+)\"");

    @Test
    void declaresEveryCommandForTheNativeImage() throws IOException {
        Set<String> declared = declaredTypes();

        for (String command : List.of("RootCommand", "CheckCommand", "BaselineCommand", "InspectCommand",
                "ExplainCommand", "RequestOptions")) {
            String type = "sh.zolt.jarproof.cli." + command;
            assertTrue(declared.contains(type), type + " is missing from " + declared);
        }
    }

    @Test
    void declaresThePicocliInternalsTheCommandsMixIn() throws IOException {
        Set<String> declared = declaredTypes();

        assertTrue(declared.contains("picocli.CommandLine$AutoHelpMixin"), String.valueOf(declared));
    }

    private static Set<String> declaredTypes() throws IOException {
        try (InputStream stream = NativeReflectionConfigTest.class.getResourceAsStream(CONFIG)) {
            assertNotNull(stream, CONFIG + " is generated by the picocli-codegen annotation processor");
            Matcher names = NAME.matcher(new String(stream.readAllBytes(), StandardCharsets.UTF_8));
            Set<String> declared = new LinkedHashSet<>();
            while (names.find()) {
                declared.add(names.group(1));
            }
            return declared;
        }
    }
}
